import numpy as np
import random

m = int(input("enter the number of machines: "))
h = int(input("enter the number of hours: "))
hunter = []
try:
  for i in range(m):
    ho =[]
    print(f"Details for hour {i+1}\n generated by system")
    for j in range(h):
      hr = random.randint(20,100)
      ho.append(hr)
    hunter.append(ho)
except Exception as e:
  print(e)
print(hunter)
if hunter:
  arr = np.array(hunter)
  print(arr)
else:
  print("no data")
avg_row = np.mean(arr,axis = 1)
avg_col = np.mean(arr, axis = 0)
global_mean = np.mean(arr)
print(f"Average in row wise order is {avg_row} and Average in coluumn wise is {avg_col}")
print(f"global mean: {global_mean}")
anomalies = np.where(arr > (2 * global_mean))
print(f"Anomaly coordnates (machine , hour): {list(zip(*anomalies))}")
